on:
  push:
    branches:
      - master
  pull_request:
    # Sequence of patterns matched against refs/tags
  release:
    types: [ published ]

name: Build artifacts

jobs:
  build:
    name: Upload nginx configuration artifacts
    runs-on: ubuntu-latest
    environment: AWS_ARTIFACT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate artifacts
        run: |
          bash generate_artifact.sh
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: ${{ github.event_name == 'release' }}
      - name: Upload Archive Node Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./radixdlt-nginx-archive-conf.zip
          asset_name: radixdlt-nginx-archive-conf.zip
          asset_content_type: application/zip
        if: ${{ github.event_name == 'release' }}
      - name: Upload Full Node Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./radixdlt-nginx-fullnode-conf.zip
          asset_name: radixdlt-nginx-fullnode-conf.zip
          asset_content_type: application/zip
        if: ${{ github.event_name == 'release' }}


      - name: set branchname with commit
        run: |
            BRANCH_NAME_WITH_HYPENS=$(git rev-parse --abbrev-ref HEAD | sed 's/\//-/g')
            COMMIT=$(git log -1 --format=%h )
            BRANCH_WITH_COMMIT=$BRANCH_NAME_WITH_HYPENS-$COMMIT
            echo "BRANCH_WITH_COMMIT=$BRANCH_WITH_COMMIT" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
      - name: Upload Archive Node zip file to aws
        run: aws s3 sync  ./ s3://${{secrets.ARTIFACT_AWS_BUCKET }}/nginx/${{env.BRANCH_WITH_COMMIT}} --delete  --exclude='*' --include='*/radixdlt-nginx-archive-conf.zip'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY}}
        if: ${{ github.event_name == 'pull_request' }}
      - name: Upload full node Node zip file to aws
        uses: actions/upload-release-asset@v1
        with:
          aws_key_id: ${{ secrets.ARTIFACT_AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.ARTIFACT_AWS_BUCKET }}
          source_dir: 'radixdlt-nginx-fullnode-conf.zip'
          destination_dir: ${{env.BRANCH_WITH_COMMIT}}
        if: ${{ github.event_name == 'pull_request' }}


  docker:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    environment: publish-dockerhub
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Environment Variables
        run: |
          GH_EVENT_NAME="${{ github.event_name }}"
          BRANCH_REF="${{github.ref}}"
          GIT_HUB_RELEASE_TAG=${{ github.event.release.tag_name }}
          set_image_version(){
              # $1 github event name , $2 branch ref value, $3 github release tag

                if [[ ! -z $1 ]] && [[ "$1" == "release" ]];then
                  echo "Workflow triggered by a release event"
                  NGINX_IMG_VERSION="$3"
                elif [[ ! -z $2 ]] && [[ "$2" == "refs/heads/master" ]];then
                  echo "Merge to master"
                  NGINX_IMG_VERSION="development-latest"
                elif [[ ! -z $1  ]] && [[ "$1" == "pull_request" ]];then
                    echo "Pull request"
                    BRANCH_NAME_WITH_HYPENS=$(git rev-parse --abbrev-ref HEAD | sed 's/\//-/g')
                    COMMIT=$(git log -1 --format=%h )
                    NGINX_IMG_VERSION=$BRANCH_NAME_WITH_HYPENS-$COMMIT
                fi
              }

          set_image_version $GH_EVENT_NAME $BRANCH_REF $GIT_HUB_RELEASE_TAG
          echo "Image tag: $NGINX_IMG_VERSION"
          echo "NGINX_IMG_VERSION=$NGINX_IMG_VERSION" >> $GITHUB_ENV
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.alpine
          push: true
          tags: |
            radixdlt/radixdlt-nginx:${{ env.NGINX_IMG_VERSION }}
