name: create-rc-tag
#This event is triggered when a release branch is created in radixdlt/radixdlt
on:
  repository_dispatch:
    types: [rc_tag]

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  publish:
    runs-on: ubuntu-latest
    name: Add tag
    steps:
      - name: Get release name from ${{ github.event.client_payload.ref }}
        run: |
          release_branch_ref=${{ github.event.client_payload.ref }}
          release_version=${release_branch_ref/refs\/heads\/release\//}
          echo "Release version: $release_version"
          rc_tag="$release_version-rc.1"
          echo "RC_TAG=$rc_tag" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tag snapshot
        uses: simpleactions/create-tag@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RC_TAG }}