on:
  push:
    branches:
      - master
name: Test environment

jobs:
  build:
    name: Print secrets
    runs-on: ubuntu-latest
    environment: publish-dockerhub
    steps:
      - name: echo
        run: |
          echo "GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}"
          echo "DOCKERHUB_USERNAME ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN ${{ secrets.DOCKERHUB_TOKEN }}"
  docker:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    environment: publish-dockerhub
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}